/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 interior.glb
Author: tediuminteractive (https://sketchfab.com/tediuminteractive)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-interior-items-6542c39c66394888994d7343fd03fdef
Title: Fantasy Interior Items
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props : any) {
  const { nodes , materials } :any = useGLTF('./interior.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[410.777, 74, 34.282]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Book_Open_Leather_0.geometry} material={materials.Leather} />
            <mesh geometry={nodes.Book_Open_Paper_0.geometry} material={materials.Paper} />
          </group>
          <group position={[-97.336, 152.815, 39.157]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Bottle_2_Bottle_0.geometry} material={materials.Bottle} />
            <mesh geometry={nodes.Cork001_Wood_Planks_0.geometry} material={materials.Wood_Planks} position={[0, 0, -0.059]} scale={[0.828, 0.828, 1]} />
          </group>
          <group position={[-357.838, 304.068, 10.326]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Tapestry_Fabric_0.geometry} material={materials.Fabric} />
            <mesh geometry={nodes.bar_Wood_Planks_0.geometry} material={materials.Wood_Planks} scale={0.021} />
          </group>
          <group position={[-127.355, 152.815, 39.157]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Bottle_Bottle_0.geometry} material={materials.Bottle} />
            <mesh geometry={nodes.Cork_Wood_Planks_0.geometry} material={materials.Wood_Planks} scale={[0.828, 0.828, 1]} />
          </group>
          <group position={[370.197, 128, 40.474]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Book_Leather_0.geometry} material={materials.Leather} />
            <mesh geometry={nodes.Book_Paper_0.geometry} material={materials.Paper} />
          </group>
          <group position={[218.133, 148.143, 9.489]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Shield_Iron_0.geometry} material={materials.Iron} />
            <mesh geometry={nodes.Shield_Wood_Planks_0.geometry} material={materials.Wood_Planks} />
          </group>
          <group position={[171.297, 183.391, 9.489]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Sword_Leather_0.geometry} material={materials.Leather} />
            <mesh geometry={nodes.Sword_Iron_0.geometry} material={materials.Iron} />
          </group>
          <group position={[147.706, 0, 100]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Barrel_Wood_Planks_0.geometry} material={materials.Wood_Planks} />
            <mesh geometry={nodes.Barrel_Iron_0.geometry} material={materials.Iron} />
          </group>
          <group position={[342.531, 0, 109.489]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Bucket_Wood_Planks_0.geometry} material={materials.Wood_Planks} />
            <mesh geometry={nodes.Bucket_Iron_0.geometry} material={materials.Iron} />
          </group>
          <group position={[-257.469, 0, 109.489]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Candlestick_Floor_Iron_0.geometry} material={materials.Iron} />
            <mesh geometry={nodes.Candle001_Candle_0.geometry} material={materials.Candle} position={[-0.001, -0.001, 1.261]} />
          </group>
          <group position={[81.438, 209.147, 9.571]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Candlestick_Wall_Iron_0.geometry} material={materials.Iron} />
            <mesh geometry={nodes.Candle002_Candle_0.geometry} material={materials.Candle} position={[0.002, -0.14, -0.039]} rotation={[0, 0, -Math.PI / 2]} />
          </group>
          <group position={[-126.557, 84.97, 117.526]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Candlestick_Table_Iron_0.geometry} material={materials.Iron} />
            <mesh geometry={nodes.Candle_Candle_0.geometry} material={materials.Candle} position={[0, 0, 0.104]} rotation={[0, 0, -Math.PI / 2]} />
          </group>
          <group position={[42.531, 0, 109.489]} rotation={[-Math.PI / 2, 0, 0]} scale={91.658}>
            <group position={[0, 0.301, 0.5]} scale={0.301}>
              <mesh geometry={nodes.Lid_Wood_Planks_0.geometry} material={materials.Wood_Planks} />
              <mesh geometry={nodes.Lid_Iron_0.geometry} material={materials.Iron} />
            </group>
            <mesh geometry={nodes.Chest_Wood_Planks_0.geometry} material={materials.Wood_Planks} />
            <mesh geometry={nodes.Chest_Iron_0.geometry} material={materials.Iron} />
          </group>
          <group position={[391.85, 128, 37.314]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Scroll_Paper_0.geometry} material={materials.Paper} />
            <mesh geometry={nodes.Scroll_Fabric_0.geometry} material={materials.Fabric} />
          </group>
          <mesh geometry={nodes.Bone_Bone_0.geometry} material={materials.Bone} position={[-160.536, 87.899, 140.338]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Skull_Bone_0.geometry} material={materials.Bone} position={[-167.141, 152.815, 41.175]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Goblet_Iron_0.geometry} material={materials.Iron} position={[-126.557, 84.97, 175.901]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Knife_Iron_0.geometry} material={materials.Iron} position={[-158.078, 85.696, 191.833]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Spoon_Iron_0.geometry} material={materials.Iron} position={[-165.916, 84.97, 181.279]} rotation={[-Math.PI / 2, 0, 0]} scale={24.723} />
          <mesh geometry={nodes.Plate_Iron_0.geometry} material={materials.Iron} position={[-188.423, 85, 185.309]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Candle_2_Candle_0.geometry} material={materials.Candle} position={[-103.018, 85.149, 112.14]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Crate_Wood_Planks_0.geometry} material={materials.Wood_Planks} position={[242.531, 0, 109.489]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Chair_Wood_Planks_0.geometry} material={materials.Wood_Planks} position={[-414.831, 0, 259.489]} rotation={[-Math.PI / 2, 0, 0]} scale={100.218} />
          <mesh geometry={nodes['Table_-_Rectangular_Wood_Planks_0'].geometry} material={materials.Wood_Planks} position={[-410.732, 0, 159.489]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Stool_Wood_Planks_0.geometry} material={materials.Wood_Planks} position={[-157.469, 0, 259.489]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Table_-_Round_Wood_Planks_0'].geometry} material={materials.Wood_Planks} position={[-157.469, 0, 159.489]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Bookshelf_Wood_Planks_0.geometry} material={materials.Wood_Planks} position={[442.531, 0, 9.489]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Shelf_Wood_Planks_0.geometry} material={materials.Wood_Planks} position={[-106.352, 147.034, 9.489]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/interior.glb')
